## Customize & thirdparty plug-in settings
## Open your site tags in left sidebar.
[TagsCloud]
  Enable = true
  Limit = 10

## Open share plug-in which can easy share your article to more kind of media.
[Share]
  Enable = false
  AddthisId = "Your AddthisId"

## Open comment to communicate with reader.
[Comment]
  Enable = false
  Module = "Waline"
  ## If module is LiveRe need add your LiveRedId, see https://livere.com/.
  LiveReId = "Your LiveReId"
  ## If module is Waline need add your walin backend server url, see https://waline.js.org/
  WalineSerURL = "Your waline server URL"

  # If module is "Utterances",see https://utteranc.es/
  UtterancesRepo = "owner/repo"
  UtterancesTheme = "github-light"
  UtterancesTitle = "pathname"

## When comment module isn't waline, there need add leancloud server settings which use record vistors.
[LeanCloud]
  AppId = "Your LCAppId"
  AppKey = "Your LCAppKey"
  ServerURL = "Your LCServer"

## Website PV & UV statis engine
[Statis]
  BusuanziCounter = true
#  CNNZSiteId = "Your CNNZSiteId"
#  BaiduSiteId = "Your BaiduSiteId"
#  GoogleSiteId = "Your GoogleSiteId"

## Add DaoVoice online chat component, see http://account.daocloud.io/signup.
[OnlineIM]
  Enable = false
#  DaoVoiceId = "Your DaoVoiceId"

## 3D map display visitor location.
[Others]
#  RevolverMapId = "Your RevolverMapId"